spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #    schema: classpath:form-schema.sql
    #    data: classpath:form-data.sql
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 3000
      read-only: false
      login-timeout: 5



#虽然两种都可以运行成功，但下面这种写法才是2.4版本的最好的写法，原因是2.4版本中官方将配置文件的加载进行了更新，
#所以如果使用的是2.4版本推荐用下面的这种写法，至于原因就是为了提升对 Kubernetes 的原生支持而作的修改
#spring:
#  profiles: pro
---
#生产环境
spring:
  config:
    activate:
      on-profile: pro
  datasource:
    url: jdbc:mysql://101.35.194.46:3306/nezhadb?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: nezha
    password: 7fFsECXmpjX5y3Xw

---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
  datasource:
    url: jdbc:mysql://sh-cdb-1qjrazc8.sql.tencentcdb.com:63915/dxz?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: admin
    password: dxzsaas@!

---
#开发环境
spring:
  #  profiles: dev
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://101.35.194.46:3306/nezhadb?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: nezha
    password: 7fFsECXmpjX5y3Xw



---
#本地环境
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://101.35.194.46:3306/nezhadb?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: admin
    password: 7fFsECXmpjX5y3Xw
