mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO
      insert-strategy: not_empty
      update-strategy: not_empty
      # 表统一加前缀
    #      table-prefix:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    multiple-result-sets-enabled: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

#虽然两种都可以运行成功，但下面这种写法才是2.4版本的最好的写法，原因是2.4版本中官方将配置文件的加载进行了更新，
#所以如果使用的是2.4版本推荐用下面的这种写法，至于原因就是为了提升对 Kubernetes 的原生支持而作的修改
#spring:
#  profiles: pro
---
#生产环境
spring:
  config:
    activate:
      on-profile: pro



---
#开发环境
spring:
  config:
    activate:
      on-profile: sit


---
#开发环境
spring:
  config:
    activate:
      on-profile: dev

---
#本地环境
spring:
  config:
    activate:
      on-profile: local
